// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMnOcw9nC5JFD5XzWw1dDH25ItNoPgjEk',
    appId: '1:133621180495:web:1debf1fed2e5c55c08e23a',
    messagingSenderId: '133621180495',
    projectId: 'survly',
    authDomain: 'survly.firebaseapp.com',
    storageBucket: 'survly.appspot.com',
    measurementId: 'G-CKGYKJ3P3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArVpABWWml4AWcUSx4b58oS1F2b_Bpn94',
    appId: '1:133621180495:android:5f368ce5686c394308e23a',
    messagingSenderId: '133621180495',
    projectId: 'survly',
    storageBucket: 'survly.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByt7j-zxDadAL6qDSI66qWMCrAJDMt2kE',
    appId: '1:133621180495:ios:904bf3b4d643265d08e23a',
    messagingSenderId: '133621180495',
    projectId: 'survly',
    storageBucket: 'survly.appspot.com',
    iosBundleId: 'com.example.survly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByt7j-zxDadAL6qDSI66qWMCrAJDMt2kE',
    appId: '1:133621180495:ios:ce6b9dfc41b4881f08e23a',
    messagingSenderId: '133621180495',
    projectId: 'survly',
    storageBucket: 'survly.appspot.com',
    iosBundleId: 'com.example.survly.RunnerTests',
  );
}
