# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Distribute to Firebase"
  lane :firebase do
    sh "flutter build apk --release"
    release = firebase_app_distribution(
      app: "1:133621180495:android:5f368ce5686c394308e23a",
      # testers: "thanhtan27032001@gmail.com",
      groups: "testers",
      release_notes: "Auto deploy using fastlane",
      android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
      firebase_cli_token: "1//0gIoYrxxwWZyxCgYIARAAGBASNwF-L9IrHmjz6aiGeyj75NHs1udR6uklbBvjJ3Pmnc91U2AZqxnlZpALFR5aVToPLAgBdvc7zzk"
    )
  end

  desc "Distribute to Firebase in fake main branch"
  lane :firebase_fake do
    sh "flutter build apk --release"
    release = firebase_app_distribution(
      app: "1:133621180495:android:5f368ce5686c394308e23a",
      groups: "testers",
      release_notes: "Auto deploy using fastlane",
      android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
      firebase_cli_token: "1//0gIoYrxxwWZyxCgYIARAAGBASNwF-L9IrHmjz6aiGeyj75NHs1udR6uklbBvjJ3Pmnc91U2AZqxnlZpALFR5aVToPLAgBdvc7zzk"
    )
  end
end
